version: '3.8'

services:
   mysql-server:
      image: mysql:8
      container_name: cont-mysqlserver
      environment:
         - MYSQL_ROOT_PASSWORD=proyectofinal12345
         - MYSQL_USER=adminUser
         - MYSQL_PASSWORD=proyectofinal12345
         - MYSQL_DATABASE=db_store
      ports:
         - '3308:3306'
      networks:
         - net-mysql-server
      volumes:
         - data-mysql-volume:/var/lib/mysql

networks:
   net-mysql-server:

volumes:
   data-mysql-volume:
