export enum DomainExceptionCode {
   DEFAULT_DOMAIN_EXCEPTION = 'DEFAULT_DOMAIN_EXCEPTION',
   PURCHASE_CUSTOMER_ID_REQUIRED = 'USER_NAME_REQUIRED',
   PURCHASE_PAYMENT_METHOD_REQUIRED = 'USER_LASTNAME_REQUIRED',
   PURCHASE_CUSTOMER_ID_INVALID = 'USER_EMAIL_INVALID',
   PURCHASE_CUSTOMER_NOT_FOUND = 'USER_CUSTOMER_NOT_FOUND',
   PURCHASE_PAYMENT_METHOD_INVALID = 'USER_PAYMENT_METHOD_INVALID',
   PURCHASE_GUID_INVALID = 'USER_GUID_INVALID',
   PURCHASE_NOT_FOUND = 'USER_NOT_FOUND',
}
