export enum DomainExceptionCode {
   DEFAULT_DOMAIN_EXCEPTION = 'DEFAULT_DOMAIN_EXCEPTION',
   CUSTOMER_USER_ID_REQUIRED = 'CUSTOMER_USER_ID_REQUIRED',
   CUSTOMER_ADDRESS_REQUIRED = 'CUSTOMER_ADDRESS_REQUIRED',
   CUSTOMER_DNI_REQUIRED = 'CUSTOMER_DNI_REQUIRED',
   CUSTOMER_GUID_INVALID = 'CUSTOMER_GUID_INVALID',
   CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
}
